<?xml version="1.0"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.cloudscheduler</groupId><artifactId>cloud-task-scheduling</artifactId><version>1.0.0</version></parent><artifactId>server</artifactId><dependencies><dependency><groupId>com.cloudscheduler</groupId><artifactId>core</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId><version>${spring-boot.version}</version></plugin></plugins></build></project>
